name: flutter_otk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  get: ^4.6.6
  flutter_widget_from_html: ^0.15.3
  dio: ^5.7.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - images/

fonts:
  - family: Prompt
    fonts:
      - asset: assets/fonts/Prompt-Regular.ttf


